pyodbc.cpython-38-x86_64-linux-gnu.so,sha256=6ys_cvCbKw70IHulumI3aSJDC69xLDONzCh6LQLYh5c,691992
pyodbc-4.0.28.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.28.dist-info/METADATA,sha256=DeSMA7j3wJqRCvdr5lGquEgusPf6P1EXGJCIVMc8Ock,1062
pyodbc-4.0.28.dist-info/WHEEL,sha256=p8ZXqRNa6rvGUTeJXlsqY-3rQZhTFtu81tHWmXJHvgA,103
pyodbc-4.0.28.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc-4.0.28.dist-info/INSTALLER,sha256=k2HakvNQqKWNOOaXxC2-byn7Nv92WdQeqJEqiZGmGmA,12
pyodbc-4.0.28.dist-info/RECORD,,
